//No SRAMIF in NVDLA Small
/*#ifndef NVDLA_SRAMIF_HEADER*/
/*#define NVDLA_SRAMIF_HEADER*/
/*#define SRAMIF_CFG_RD_WEIGHT_0 0x3000*/
/*#define SRAMIF_CFG_RD_WEIGHT_1 0x3004*/
/*#define SRAMIF_CFG_RD_WEIGHT_2 0x3008*/
/*#define SRAMIF_CFG_WR_WEIGHT_0 0x300c*/
/*#define SRAMIF_CFG_WR_WEIGHT_1 0x3010*/
/*#define SRAMIF_CFG_OUTSTANDING_CNT 0x3014*/
/*#define SRAMIF_STATUS 0x3018*/
/*#endif*/
