#ifndef NVDLA_CDP_RDMA_HEADER
#define NVDLA_CDP_RDMA_HEADER
#define CDP_RDMA_S_STATUS 0xc000
#define CDP_RDMA_S_POINTER 0xc004
#define CDP_RDMA_D_OP_ENABLE 0xc008
#define CDP_RDMA_D_DATA_CUBE_WIDTH 0xc00c
#define CDP_RDMA_D_DATA_CUBE_HEIGHT 0xc010
#define CDP_RDMA_D_DATA_CUBE_CHANNEL 0xc014
#define CDP_RDMA_D_SRC_BASE_ADDR_LOW 0xc018
#define CDP_RDMA_D_SRC_BASE_ADDR_HIGH 0xc01c
#define CDP_RDMA_D_SRC_LINE_STRIDE 0xc020
#define CDP_RDMA_D_SRC_SURFACE_STRIDE 0xc024
#define CDP_RDMA_D_SRC_DMA_CFG 0xc028
#define CDP_RDMA_D_SRC_COMPRESSION_EN 0xc02c
#define CDP_RDMA_D_OPERATION_MODE 0xc030
#define CDP_RDMA_D_DATA_FORMAT 0xc034
#define CDP_RDMA_D_PERF_ENABLE 0xc038
#define CDP_RDMA_D_PERF_READ_STALL 0xc03c
#endif
